# -- Starship Config: Clean, Functional, Aesthetic --
# Author: Luffie Edition
# ───────────────────────────────
# GLOBAL CONFIG
# ───────────────────────────────
add_newline = false
command_timeout = 1000
format = """
$username$hostname$directory$git_branch$git_state$git_status
$character
"""
right_format = """
$cmd_duration$custom.ms
"""

# ───────────────────────────────
# PROMPT MODULES
# ───────────────────────────────
[character]
success_symbol = "[❯](bold green)"
error_symbol = "[❯](bold red)"
vicmd_symbol = "[❮](bold yellow)"

[directory]
style = "bold cyan"
#format = "[$path]($style) "
truncation_length = 3
truncate_to_repo = false

# Username and hostname modules
[username]
style_user = "bold blue"
style_root = "red bold"
format = "[$user]($style)"
disabled = false
show_always = true

[hostname]
format = "@(dimmed white)[$hostname](bold green): "
ssh_only = false
disabled = false

[git_branch]
format = "[$branch]($style) "
#symbol = " "
style = "bright black"

[git_status]
format = '([$conflicted$diverged$ahead_behind$stashed$untracked$modified$staged]($style))'
style = 'bold purple'
conflicted = '✘'  # Merge conflict symbol
diverged = '⇕'    # Diverged branches symbol
ahead = '⇡'       # Ahead of remote symbol
behind = '⇣'      # Behind remote symbol
stashed = '$'   # Stashed changes symbol
untracked = '?'   # Untracked files symbol
modified = '!'    # Modified files symbol
staged = '+'      # Staged files symbol

[cmd_duration]
min_time = 1000
format = "[⏱ $duration]($style)"
style = "dimmed blue"

# ───────────────────────────────
# CUSTOM LATENCY MODULE
# ───────────────────────────────
# Displays ping latency (example: Cloudflare DNS)
[custom.latency]
command = "ping -c 1 -W 1 1.1.1.1 2>/dev/null | awk -F'[=.]' '/time=/{print $2; exit}' || echo 'N/A'"
when = "true"
format = "[$output]($style)"
style = "dimmed green"
description = "Network latency check"
